export const FAQ_CATEGORIES_RH = [
  { id: 'rh-users', label: 'Gestion des agents' },
  { id: 'rh-soldes', label: 'Soldes & CET' },
  { id: 'rh-demandes', label: 'Demandes & validations' },
  { id: 'rh-cet', label: 'Demandes CET' },
  { id: 'rh-recup', label: 'Récupération' },
  { id: 'rh-stats', label: 'Stats & exports' },
  { id: 'rh-divers', label: 'Divers' },
];

export const FAQ_RH = [
  // Gestion des agents (10)
  {
    id: 101,
    cat: 'rh-users',
    q: "Comment créer un nouvel agent ?",
    keywords: ['créer', 'agent', 'utilisateur', 'nouveau', 'ajouter'],
    a: "Interface RH > onglet \"Gestion des utilisateurs\" > bouton \"+ Créer un utilisateur\". Le formulaire demande nom, prénom, email, type d'utilisateur, service, poste, type de contrat, dates et quotité, et le responsable hiérarchique. Un mot de passe temporaire est généré automatiquement.",
  },
  {
    id: 102,
    cat: 'rh-users',
    q: "Comment modifier les informations d'un agent ?",
    keywords: ['modifier', 'changer', 'agent', 'fiche'],
    a: "Onglet \"Gestion des utilisateurs\" > bouton \"Modifier\" sur la ligne de l'agent. Vous pouvez ajuster nom, prénom, email, type, service, poste, type de contrat, dates, quotité et responsable hiérarchique.",
  },
  {
    id: 103,
    cat: 'rh-users',
    q: "Comment réinitialiser le mot de passe d'un agent ?",
    keywords: ['réinitialiser', 'reset', 'mot de passe', 'oublié'],
    a: "Onglet \"Gestion des utilisateurs\" > bouton \"Réinitialiser mot de passe\" sur la ligne de l'agent. Un nouveau mot de passe temporaire est généré et affiché ; transmettez-le à l'agent par un canal sécurisé. L'agent devra le changer à sa prochaine connexion.",
  },
  {
    id: 104,
    cat: 'rh-users',
    q: "Comment changer le rôle d'un agent (Employé / Responsable / RH) ?",
    keywords: ['rôle', 'type', 'changer', 'promouvoir'],
    a: "Onglet \"Gestion des utilisateurs\" > \"Modifier\" > champ \"Type d'utilisateur\". Attention : passer un agent en RH lui donne accès à toutes les données et à l'interface RH. La modification prend effet à la prochaine connexion de l'agent.",
  },
  {
    id: 105,
    cat: 'rh-users',
    q: "Comment changer le service ou le poste d'un agent ?",
    keywords: ['service', 'poste', 'mutation', 'transfert'],
    a: "Onglet \"Gestion des utilisateurs\" > \"Modifier\" > champs \"Service\" et \"Poste\". Pensez à mettre à jour aussi le \"Responsable hiérarchique\" pour que les futures demandes remontent au bon manager.",
  },
  {
    id: 106,
    cat: 'rh-users',
    q: "Comment supprimer un agent qui quitte la collectivité ?",
    keywords: ['supprimer', 'départ', 'partir', 'enlever'],
    a: "Onglet \"Gestion des utilisateurs\" > bouton \"Supprimer\" (rouge) sur la ligne de l'agent. La suppression est immédiate ; l'agent ne peut plus se connecter. L'historique de ses demandes reste cependant consultable dans \"Toutes les demandes\".",
  },
  {
    id: 107,
    cat: 'rh-users',
    q: "Un agent ne peut pas se connecter, que vérifier ?",
    keywords: ['connexion', 'connecter', 'erreur', 'bloqué'],
    a: "Vérifiez sur la fiche agent : (1) le compte n'a pas été supprimé, (2) son nom apparaît bien dans la liste de l'écran de connexion, (3) son mot de passe peut être réinitialisé via le bouton dédié pour générer un nouveau mot de passe temporaire.",
  },
  {
    id: 108,
    cat: 'rh-users',
    q: "Comment voir l'historique des demandes d'un agent ?",
    keywords: ['historique', 'agent', 'voir', 'demandes'],
    a: "Onglet \"Toutes les demandes\" : utilisez la barre de recherche pour filtrer par nom d'agent. Vous voyez toutes ses demandes (en attente, validées, refusées, annulées) avec dates, statut, validateurs et motifs.",
  },
  {
    id: 109,
    cat: 'rh-users',
    q: "Comment changer le responsable hiérarchique d'un agent ?",
    keywords: ['responsable', 'manager', 'hiérarchique', 'changer'],
    a: "Onglet \"Gestion des utilisateurs\" > \"Modifier\" > champ \"Responsable hiérarchique\" : sélectionnez parmi la liste. Toutes les futures demandes de cet agent remonteront au nouveau responsable.",
  },
  {
    id: 110,
    cat: 'rh-users',
    q: "Comment voir tous les agents en un coup d'œil ?",
    keywords: ['liste', 'tous', 'voir', 'agents'],
    a: "Onglet \"Gestion des utilisateurs\" : tableau avec nom, type, service, poste, ancienneté, type de contrat et statut de chaque agent. Pour la vue arborescente par service, utilisez l'onglet \"Organigramme\" du menu principal.",
  },

  // Soldes & CET (8)
  {
    id: 111,
    cat: 'rh-soldes',
    q: "Comment ajuster le solde CET d'un agent ?",
    keywords: ['ajuster', 'modifier', 'solde', 'cet', 'manuel'],
    a: "Onglet \"Soldes CET\" > bouton \"Ajuster\" sur la ligne de l'agent. Une fenêtre vous demande le nombre de jours et un motif. La modification est immédiate sur le solde CET.",
  },
  {
    id: 112,
    cat: 'rh-soldes',
    q: "Comment recalculer les soldes de congés ?",
    keywords: ['recalculer', 'recalcul', 'global', 'solde'],
    a: "Onglet \"Soldes CET\" > bouton global \"Recalculer tous les soldes\". L'application ré-additionne tous les jours ouvrés des demandes validées pour resynchroniser le compteur \"jours pris\" de chaque agent.",
  },
  {
    id: 113,
    cat: 'rh-soldes',
    q: "Quelle est la différence entre acquis, pris, restants et reportés ?",
    keywords: ['différence', 'acquis', 'pris', 'restants', 'reportés'],
    a: "Acquis = droits de l'année. Pris = somme des congés validés. Restants = (acquis + reportés + fractionnés) − pris. Reportés = jours de l'année précédente non consommés. Fractionnés = bonus de fractionnement.",
  },
  {
    id: 114,
    cat: 'rh-soldes',
    q: "Un agent dit que son solde est faux, comment vérifier ?",
    keywords: ['faux', 'vérifier', 'écart', 'incorrect'],
    a: "Lancez \"Recalculer tous les soldes\" depuis l'onglet \"Soldes CET\". Si l'écart persiste, comparez ses demandes validées (onglet \"Toutes les demandes\" filtré sur l'agent) avec le compteur \"jours pris\" affiché sur sa fiche Profil.",
  },
  {
    id: 115,
    cat: 'rh-soldes',
    q: "Comment voir le CET de chaque agent ?",
    keywords: ['cet', 'voir', 'tous', 'soldes', 'agents'],
    a: "Onglet \"Soldes CET\" : tableau de tous les agents avec leur solde CET (jours épargnés, jours utilisés, solde courant). Trie possible par colonne pour repérer les agents proches du plafond 60.",
  },
  {
    id: 116,
    cat: 'rh-soldes',
    q: "Comment fonctionne le report d'année en année ?",
    keywords: ['report', 'fin année', 'reporter', 'reportés'],
    a: "Le report est géré côté base de données : à la création des soldes de la nouvelle année, les jours non pris sont injectés dans la colonne \"reportés\" selon les règles de la collectivité. Il n'y a pas de bouton de clôture annuelle dans l'interface.",
  },
  {
    id: 117,
    cat: 'rh-soldes',
    q: "Que faire si un agent atteint le plafond de 60 jours sur son CET ?",
    keywords: ['plafond', '60', 'cet', 'maximum'],
    a: "Tout transfert au-delà est automatiquement bloqué côté API. Refusez la demande de transfert avec un motif explicite, et invitez l'agent à utiliser ses jours épargnés via \"Retirer des jours du CET\".",
  },
  {
    id: 118,
    cat: 'rh-soldes',
    q: "Que se passe-t-il pour le CET quand je supprime un agent ?",
    keywords: ['cet', 'supprimer', 'départ', 'liquidation'],
    a: "Le solde CET reste en base lié à l'utilisateur. Avant la suppression, ajustez ou liquidez le CET via le bouton \"Ajuster\" pour remettre à zéro et tracer le motif (ex: \"liquidation départ\").",
  },

  // Demandes & validations (10)
  {
    id: 119,
    cat: 'rh-demandes',
    q: "Comment voir toutes les demandes en cours ?",
    keywords: ['attente', 'pending', 'voir toutes', 'à valider'],
    a: "Onglet \"Toutes les demandes\" : tableau de l'ensemble des demandes, tous services confondus, avec employé, période, jours, date de demande, niveau de validation atteint et statut. Utilisez la barre de recherche pour filtrer par nom.",
  },
  {
    id: 120,
    cat: 'rh-demandes',
    q: "Comment examiner et valider une demande ?",
    keywords: ['examiner', 'valider', 'voir détail'],
    a: "Sur la liste, cliquez sur \"Examiner\" : une fenêtre affiche tous les détails (agent, dates, jours, motif, circuit). Boutons disponibles : \"Valider\", \"Refuser\" (avec motif) et \"Annuler\".",
  },
  {
    id: 121,
    cat: 'rh-demandes',
    q: "Puis-je valider directement sans passer par le N+1 ?",
    keywords: ['forcer', 'court-circuiter', 'rh', 'directement'],
    a: "Oui : sur une demande en attente, le bouton \"Forcer validation RH\" valide la demande sans attendre les niveaux intermédiaires. C'est tracé dans l'historique avec votre nom comme validateur.",
  },
  {
    id: 122,
    cat: 'rh-demandes',
    q: "Comment annuler une demande déjà validée ?",
    keywords: ['annuler', 'congé', 'validée', 'rétractation'],
    a: "Sur l'onglet \"Toutes les demandes\", la ligne d'une demande validée affiche le bouton \"Annuler congé\". Vous devez saisir un motif. Le solde de l'agent est automatiquement recrédité.",
  },
  {
    id: 123,
    cat: 'rh-demandes',
    q: "Comment refuser une demande ?",
    keywords: ['refuser', 'refus', 'rejet'],
    a: "Cliquez sur \"Examiner\" puis \"Refuser\". Vous pouvez ajouter un commentaire. Le statut passe à \"Refusée\", aucun jour n'est décompté et l'agent reçoit une notification avec votre motif.",
  },
  {
    id: 124,
    cat: 'rh-demandes',
    q: "Comment poser une demande pour un agent ?",
    keywords: ['poser pour', 'à la place', 'créer congé', 'rh-create'],
    a: "Onglet \"Créer un congé\" : sélectionnez l'agent, saisissez les dates et un motif. La demande est créée et validée d'office, le solde de l'agent est mis à jour immédiatement.",
  },
  {
    id: 125,
    cat: 'rh-demandes',
    q: "Comment modifier les dates d'une demande déjà validée ?",
    keywords: ['modifier', 'dates', 'changer', 'validée'],
    a: "Une demande validée n'est pas modifiable directement. Annulez-la (le solde est recrédité) puis recréez-en une depuis l'onglet \"Créer un congé\" avec les bonnes dates.",
  },
  {
    id: 126,
    cat: 'rh-demandes',
    q: "Comment retrouver une demande spécifique ?",
    keywords: ['rechercher', 'trouver', 'demande spécifique'],
    a: "Onglet \"Toutes les demandes\" : la barre de recherche en haut filtre par nom d'agent. Combinez avec un tri sur la date pour cibler précisément.",
  },
  {
    id: 127,
    cat: 'rh-demandes',
    q: "Que se passe-t-il après ma validation côté agent ?",
    keywords: ['après validation', 'agent', 'notification'],
    a: "L'agent reçoit une notification push (s'il a activé les notifications) et le statut de sa demande passe à \"Validée\" sur \"Mes demandes\". Le congé apparaît immédiatement sur le calendrier équipe.",
  },
  {
    id: 128,
    cat: 'rh-demandes',
    q: "Comment voir le détail du circuit de validation d'une demande ?",
    keywords: ['circuit', 'niveaux', 'historique', 'validation'],
    a: "Le circuit (Demande → N+1 → N+2 → RH) est affiché directement sur la fiche de la demande dans \"Toutes les demandes\" avec les noms des validateurs et l'étape en cours mise en évidence.",
  },

  // Demandes CET (5)
  {
    id: 129,
    cat: 'rh-cet',
    q: "Comment approuver une demande de transfert CET ?",
    keywords: ['cet', 'transfert', 'approuver', 'valider'],
    a: "Onglet \"Demandes CET\" : un badge rouge indique le nombre de demandes en attente. Pour chaque demande, vérifiez l'éligibilité (1 an d'ancienneté, 20 jours pris, max 5/an, plafond 60), puis cliquez \"Valider\". Les jours sont déduits du solde et ajoutés au CET.",
  },
  {
    id: 130,
    cat: 'rh-cet',
    q: "Comment refuser une demande CET avec un motif ?",
    keywords: ['cet', 'refuser', 'refus', 'transfert'],
    a: "Sur la demande, cliquez sur \"Refuser\" : une fenêtre vous demande de saisir un motif obligatoire (ex: \"ancienneté insuffisante\"). L'agent est notifié et la demande reste tracée dans l'historique.",
  },
  {
    id: 131,
    cat: 'rh-cet',
    q: "Quelle différence entre transfert vers CET et retrait du CET ?",
    keywords: ['transfert', 'retrait', 'verser', 'différence'],
    a: "Transfert (versement) : l'agent met des jours de congé non pris en réserve sur son CET. Retrait : l'agent récupère des jours stockés et les ramène sur son solde de congés courant pour les poser. Les deux passent par le même onglet \"Demandes CET\".",
  },
  {
    id: 132,
    cat: 'rh-cet',
    q: "Comment voir les anciennes demandes CET déjà traitées ?",
    keywords: ['historique', 'cet', 'traitées', 'passées'],
    a: "L'onglet \"Demandes CET\" liste toutes les demandes avec leur statut (en attente, validée, refusée). Les demandes traitées restent affichées avec le validateur, la date et le motif éventuel.",
  },
  {
    id: 133,
    cat: 'rh-cet',
    q: "Une demande CET reste-t-elle en attente longtemps ?",
    keywords: ['délai', 'urgent', 'rapidement'],
    a: "Aucun délai automatique n'est imposé. Le badge rouge sur l'onglet \"Demandes CET\" rappelle qu'il y a des demandes en attente — traitez-les régulièrement pour ne pas pénaliser les agents.",
  },

  // Récupération (5)
  {
    id: 134,
    cat: 'rh-recup',
    q: "Comment valider une déclaration d'heures de récupération ?",
    keywords: ['récupération', 'recup', 'valider', 'heures'],
    a: "Onglet \"Récupération\" : un badge orange indique les demandes en attente. Pour chaque déclaration, vous pouvez \"Voir document\" (PDF signé), puis \"Valider\" ou \"Refuser\" (avec motif).",
  },
  {
    id: 135,
    cat: 'rh-recup',
    q: "Quelle est la différence entre récupération en congé et rémunération ?",
    keywords: ['récupération', 'rémunération', 'choix', 'compensation'],
    a: "Lors de la déclaration, l'agent choisit : \"Récupération en congé\" (les heures viendront alimenter un compteur d'heures à utiliser plus tard) ou \"Rémunération\" (paiement en heures supplémentaires, traité hors application via la paie).",
  },
  {
    id: 136,
    cat: 'rh-recup',
    q: "Comment valider une demande d'utilisation d'heures de récupération ?",
    keywords: ['utilisation', 'utiliser', 'récupération', 'valider'],
    a: "L'onglet \"Récupération\" sépare deux blocs : les déclarations d'heures et les demandes d'utilisation. Pour une utilisation, vérifiez que l'agent a bien le solde requis puis cliquez \"Valider\".",
  },
  {
    id: 137,
    cat: 'rh-recup',
    q: "Comment voir le document officiel signé par l'agent ?",
    keywords: ['document', 'signé', 'signature', 'pdf'],
    a: "Sur la ligne d'une déclaration, cliquez sur \"Voir document\" : le PDF officiel s'affiche avec en-tête Mairie de Chartrettes, détails de l'heure supplémentaire, type de compensation et signature numérique de l'agent.",
  },
  {
    id: 138,
    cat: 'rh-recup',
    q: "Que se passe-t-il quand je refuse une déclaration de récupération ?",
    keywords: ['refuser', 'récupération', 'refus'],
    a: "Le statut passe à \"Refusée\", l'agent reçoit une notification avec votre motif. Aucune heure n'est créditée à son compteur. Il peut soumettre une nouvelle déclaration corrigée.",
  },

  // Stats & exports (5)
  {
    id: 139,
    cat: 'rh-stats',
    q: "Comment exporter les données ?",
    keywords: ['exporter', 'export', 'csv', 'excel', 'pdf'],
    a: "Onglet \"📊 Statistiques avancées\" : boutons \"Export Excel\" et \"Export PDF\" en haut. Choisissez l'année dans le sélecteur. Le fichier contient KPIs, graphiques et le tableau détaillé par type d'utilisateur.",
  },
  {
    id: 140,
    cat: 'rh-stats',
    q: "Quels indicateurs trouve-t-on dans les statistiques avancées ?",
    keywords: ['kpi', 'indicateurs', 'stats', 'globaux'],
    a: "Trois cartes KPI : délai moyen de validation, taux d'utilisation moyen et durée moyenne des congés. Quatre graphiques : analyse trimestrielle, durée moyenne par type, jours de départ préférés (lundi/mardi…) et taux d'utilisation par catégorie d'agent.",
  },
  {
    id: 141,
    cat: 'rh-stats',
    q: "Puis-je filtrer les stats par année ?",
    keywords: ['année', 'filtrer', 'période', 'sélecteur'],
    a: "Oui : un sélecteur d'année (2024, 2025, 2026, 2027) en haut de l'onglet \"Statistiques avancées\" recharge tous les indicateurs et graphiques sur l'année choisie.",
  },
  {
    id: 142,
    cat: 'rh-stats',
    q: "Comment savoir qui valide le plus vite ou le plus lentement ?",
    keywords: ['délai', 'validation', 'rapidité', 'manager'],
    a: "Le KPI \"Délai moyen de validation\" donne la tendance globale. Pour le détail par responsable, croisez l'onglet \"Toutes les demandes\" (date de demande vs date de validation) avec la fiche de chaque agent.",
  },
  {
    id: 143,
    cat: 'rh-stats',
    q: "Comment voir les services qui consomment le plus de congés ?",
    keywords: ['service', 'consommation', 'top', 'classement'],
    a: "Le tableau détaillé en bas de l'onglet \"Statistiques avancées\" ventile les jours pris et le taux d'utilisation par type d'utilisateur. Les barres de progression facilitent la comparaison.",
  },

  // Divers (7)
  {
    id: 144,
    cat: 'rh-divers',
    q: "Comment sont gérés les jours fériés ?",
    keywords: ['jours fériés', 'férié', 'gérer'],
    a: "Les jours fériés sont synchronisés automatiquement avec l'API officielle du gouvernement français (calendrier.api.gouv.fr/jours-feries/metropole). Aucune saisie manuelle n'est nécessaire ; les calendriers les affichent et les exclut du décompte des jours ouvrés.",
  },
  {
    id: 145,
    cat: 'rh-divers',
    q: "Comment l'application gère-t-elle le délai de 7 jours d'avance ?",
    keywords: ['délai', '7 jours', 'avance', 'préavis'],
    a: "Le délai est appliqué côté API : toute demande créée par un agent à moins de 7 jours du début est rejetée avec un message explicite. La règle ne s'applique pas aux demandes créées en mode RH (\"Créer un congé\"), qui sont validées d'office.",
  },
  {
    id: 146,
    cat: 'rh-divers',
    q: "Comment sont calculés les jours de fractionnement ?",
    keywords: ['fractionnement', 'bonus', 'jours sup'],
    a: "Si un agent prend 3 à 5 jours de congés en dehors de la période mai-octobre, il gagne 1 jour bonus ; au-delà de 5 jours, +2 jours. Le calcul est automatique côté API et alimente la colonne \"jours fractionnés\" de son solde.",
  },
  {
    id: 147,
    cat: 'rh-divers',
    q: "Comment voir l'organigramme de la collectivité ?",
    keywords: ['organigramme', 'arbre', 'hiérarchie'],
    a: "Onglet \"Organigramme\" du menu principal : vue arborescente cliquable, zoom et impression. Le bouton \"Imprimer / PDF\" propose plusieurs presets (complet, Direction, École, Services Techniques).",
  },
  {
    id: 148,
    cat: 'rh-divers',
    q: "Y a-t-il une page de configuration générale ?",
    keywords: ['configuration', 'paramètres', 'settings', 'admin'],
    a: "Non, il n'existe pas de page \"Paramètres\" dans la version actuelle. Les règles métiers (délais, plafonds CET, règles de fractionnement, jours fériés) sont gérées côté code et synchronisations API. Toute modification structurelle nécessite une intervention technique.",
  },
  {
    id: 149,
    cat: 'rh-divers',
    q: "Comment les agents reçoivent-ils les notifications de validation ?",
    keywords: ['notifications', 'push', 'agents'],
    a: "Les agents qui ont activé la cloche dans la barre de navigation reçoivent une notification push à chaque étape (création, validation, refus, annulation). Sur mobile, ces notifications s'affichent comme celles d'une vraie app via le PWA.",
  },
  {
    id: 150,
    cat: 'rh-divers',
    q: "Comment sauvegarder les données ?",
    keywords: ['sauvegarde', 'backup', 'base'],
    a: "La base de données est hébergée sur Turso (LibSQL) qui assure des sauvegardes automatiques. Pour un export ponctuel des données métier, utilisez \"Export Excel\" ou \"Export PDF\" depuis l'onglet \"Statistiques avancées\".",
  },
];
