export const FAQ_CATEGORIES_RH = [
  { id: 'rh-users', label: 'Gestion des agents' },
  { id: 'rh-soldes', label: 'Gestion des soldes' },
  { id: 'rh-demandes', label: 'Demandes & validations' },
  { id: 'rh-cet', label: 'CET' },
  { id: 'rh-stats', label: 'Stats & exports' },
  { id: 'rh-hierarchy', label: 'Hiérarchie' },
  { id: 'rh-config', label: 'Config & système' },
];

export const FAQ_RH = [
  // Gestion des agents (10)
  {
    id: 101,
    cat: 'rh-users',
    q: "Comment créer un nouvel agent ?",
    keywords: ['créer', 'agent', 'utilisateur', 'nouveau', 'ajouter'],
    a: "Interface RH > onglet \"Utilisateurs\" > \"Nouvel utilisateur\". Saisissez nom, prénom, email, type (Employé/Responsable/RH), service. Un mot de passe temporaire est généré et affiché une seule fois — communiquez-le à l'agent par un canal sécurisé.",
  },
  {
    id: 102,
    cat: 'rh-users',
    q: "Comment désactiver un agent qui quitte la collectivité ?",
    keywords: ['désactiver', 'supprimer', 'départ', 'partir', 'archiver'],
    a: "Préférez la désactivation à la suppression pour conserver l'historique. Sur la fiche agent, cliquez sur \"Désactiver\" : il ne pourra plus se connecter mais ses demandes restent visibles dans les archives.",
  },
  {
    id: 103,
    cat: 'rh-users',
    q: "Comment réinitialiser le mot de passe d'un agent ?",
    keywords: ['réinitialiser', 'reset', 'mot de passe', 'oublié'],
    a: "Sur la fiche agent, bouton \"Réinitialiser mot de passe\". Un nouveau mot de passe temporaire est généré ; l'agent devra le changer à sa prochaine connexion.",
  },
  {
    id: 104,
    cat: 'rh-users',
    q: "Comment changer le rôle d'un agent (Employé → Responsable → RH) ?",
    keywords: ['rôle', 'type', 'changer', 'promouvoir'],
    a: "Sur la fiche agent, modifiez le champ \"Type d'utilisateur\". Attention : passer un agent en RH lui donne accès à toutes les données. La modification prend effet à la prochaine connexion.",
  },
  {
    id: 105,
    cat: 'rh-users',
    q: "Comment changer le service d'un agent ?",
    keywords: ['service', 'changer', 'mutation', 'transfert'],
    a: "Sur la fiche agent, modifiez \"Service\". Pensez à mettre à jour aussi son responsable hiérarchique pour que les futures demandes remontent au bon manager.",
  },
  {
    id: 106,
    cat: 'rh-users',
    q: "Comment importer plusieurs agents en une fois ?",
    keywords: ['importer', 'import', 'csv', 'masse', 'plusieurs'],
    a: "Interface RH > \"Utilisateurs\" > \"Importer CSV\". Le fichier doit contenir : nom, prenom, email, type, service. Chaque ligne crée un agent avec un mot de passe temporaire.",
  },
  {
    id: 107,
    cat: 'rh-users',
    q: "Un agent ne peut pas se connecter, que vérifier ?",
    keywords: ['connexion', 'connecter', 'erreur', 'bloqué'],
    a: "Vérifiez : (1) le compte n'est pas désactivé, (2) l'email saisi correspond à celui en base, (3) le mot de passe temporaire n'a pas expiré, (4) aucune session n'est en cours sur un autre poste.",
  },
  {
    id: 108,
    cat: 'rh-users',
    q: "Comment voir l'historique d'un agent ?",
    keywords: ['historique', 'audit', 'voir'],
    a: "Sur la fiche agent, onglet \"Historique\" : affiche toutes les demandes (validées, refusées, annulées), les ajustements de solde et les changements de rôle, avec dates et auteurs.",
  },
  {
    id: 109,
    cat: 'rh-users',
    q: "Puis-je supprimer définitivement un agent ?",
    keywords: ['supprimer', 'définitif', 'effacer', 'rgpd'],
    a: "Oui, mais cela efface aussi son historique. À réserver aux suppressions RGPD justifiées. Préférez la désactivation pour conserver les statistiques. La suppression est irréversible.",
  },
  {
    id: 110,
    cat: 'rh-users',
    q: "Comment modifier l'email d'un agent ?",
    keywords: ['email', 'modifier', 'adresse', 'mail'],
    a: "Sur la fiche agent, modifiez le champ email. C'est lui qui sert d'identifiant de connexion : informez l'agent du changement avant de l'enregistrer.",
  },

  // Gestion des soldes (10)
  {
    id: 111,
    cat: 'rh-soldes',
    q: "Comment ajuster manuellement le solde d'un agent ?",
    keywords: ['ajuster', 'modifier', 'solde', 'manuel'],
    a: "Interface RH > \"Soldes\" > sélectionnez l'agent > modifiez \"Jours acquis\", \"Jours pris\" ou \"Jours reportés\". Saisissez un motif obligatoire ; la modification est tracée dans l'historique.",
  },
  {
    id: 112,
    cat: 'rh-soldes',
    q: "Comment effectuer le report de fin d'année ?",
    keywords: ['report', 'fin année', 'rollover', 'janvier'],
    a: "En janvier, lancez \"Clôture annuelle\" depuis l'interface RH. Les jours non pris sont automatiquement reportés selon les règles configurées (plafond, dates limites). Vérifiez les exports avant validation.",
  },
  {
    id: 113,
    cat: 'rh-soldes',
    q: "Comment initialiser le solde de tous les agents en début d'année ?",
    keywords: ['initialiser', 'début année', 'tous', 'masse', '25 jours'],
    a: "Interface RH > \"Soldes\" > \"Initialiser l'année\". Saisissez les jours acquis par défaut (25 généralement) ; l'application crée une ligne par agent actif pour la nouvelle année.",
  },
  {
    id: 114,
    cat: 'rh-soldes',
    q: "Quelle est la différence entre acquis, pris, restants et reportés ?",
    keywords: ['différence', 'acquis', 'pris', 'restants', 'reportés'],
    a: "Acquis = droits de l'année en cours. Pris = somme des congés validés. Restants = acquis + reportés − pris. Reportés = jours de l'année précédente non consommés (dans la limite réglementaire).",
  },
  {
    id: 115,
    cat: 'rh-soldes',
    q: "Comment recalculer un solde si je suspecte une erreur ?",
    keywords: ['recalculer', 'erreur', 'solde', 'bug'],
    a: "Sur la fiche solde, bouton \"Recalculer\". Le système ré-additionne tous les `nombre_jours_ouvres` des demandes validées de l'année. Si l'écart persiste, vérifiez les demandes annulées.",
  },
  {
    id: 116,
    cat: 'rh-soldes',
    q: "Un agent dit que son solde est faux, comment vérifier ?",
    keywords: ['faux', 'vérifier', 'écart', 'incorrect'],
    a: "Ouvrez sa fiche, comparez \"Jours pris\" avec la liste des demandes validées. Si écart : recalculez. Sinon, l'agent confond peut-être jours ouvrés et jours calendaires.",
  },
  {
    id: 117,
    cat: 'rh-soldes',
    q: "Comment ajouter des jours bonus (ancienneté, fractionnement) ?",
    keywords: ['bonus', 'ancienneté', 'fractionnement', 'ajouter jours'],
    a: "Modifiez \"Jours acquis\" sur la fiche solde et indiquez le motif (\"+2 ancienneté\", \"+1 fractionnement\"). Le total est mis à jour immédiatement.",
  },
  {
    id: 118,
    cat: 'rh-soldes',
    q: "Comment voir l'historique des modifications de solde ?",
    keywords: ['historique', 'modifications', 'solde', 'audit'],
    a: "Sur la fiche solde, onglet \"Historique\" : chaque ligne indique date, auteur, ancien et nouveau solde, motif. Sert de preuve en cas de contestation.",
  },
  {
    id: 119,
    cat: 'rh-soldes',
    q: "Que faire si un agent a un solde négatif ?",
    keywords: ['négatif', 'dépassement', 'moins'],
    a: "L'application empêche normalement de poser plus de jours qu'on n'en possède. Un négatif vient soit d'un ajustement RH manuel, soit d'une régularisation post-validation. Recalculez et corrigez si besoin.",
  },
  {
    id: 120,
    cat: 'rh-soldes',
    q: "Comment limiter les jours reportables d'une année sur l'autre ?",
    keywords: ['plafond', 'limite', 'reportés', 'reportables'],
    a: "Le plafond de report est défini dans les paramètres de la collectivité. Lors de la clôture annuelle, l'application tronque automatiquement les reports au plafond (ex: 5 jours max).",
  },

  // Demandes & validations (10)
  {
    id: 121,
    cat: 'rh-demandes',
    q: "Comment voir toutes les demandes en attente ?",
    keywords: ['attente', 'pending', 'voir toutes', 'à valider'],
    a: "Interface RH > \"Demandes\" > filtre \"En attente\". Vous voyez toutes les demandes en cours, tous services confondus, avec délai depuis la soumission.",
  },
  {
    id: 122,
    cat: 'rh-demandes',
    q: "Puis-je valider une demande à la place du responsable hiérarchique ?",
    keywords: ['valider', 'place', 'manager', 'forcer'],
    a: "Oui, en tant que RH vous pouvez valider directement n'importe quelle demande. C'est tracé dans l'historique avec votre nom comme validateur.",
  },
  {
    id: 123,
    cat: 'rh-demandes',
    q: "Comment refuser une demande validée par un manager ?",
    keywords: ['refuser', 'override', 'annuler validation'],
    a: "Ouvrez la demande, cliquez sur \"Annuler\" puis \"Refuser\". Saisissez un motif clair : l'agent reçoit une notification avec votre justification.",
  },
  {
    id: 124,
    cat: 'rh-demandes',
    q: "Comment poser une demande pour un agent ?",
    keywords: ['poser pour', 'à la place', 'rh-create'],
    a: "Interface RH > \"Nouvelle demande\" > sélectionnez l'agent. La demande est validée d'office (pas de circuit hiérarchique) et le solde de l'agent est mis à jour immédiatement.",
  },
  {
    id: 125,
    cat: 'rh-demandes',
    q: "Comment modifier les dates d'une demande validée ?",
    keywords: ['modifier', 'dates', 'changer', 'validée'],
    a: "Une demande validée n'est pas modifiable directement. Annulez-la (le solde est recrédité) puis créez-en une nouvelle avec les bonnes dates en mode RH (validation immédiate).",
  },
  {
    id: 126,
    cat: 'rh-demandes',
    q: "Comment annuler une demande validée ?",
    keywords: ['annuler', 'validée', 'rétractation'],
    a: "Ouvrez la demande, bouton \"Annuler\". Le statut passe à \"annulée\", le solde de l'agent est automatiquement recrédité du nombre de jours ouvrés.",
  },
  {
    id: 127,
    cat: 'rh-demandes',
    q: "Comment filtrer les demandes par service ?",
    keywords: ['filtrer', 'service', 'tri'],
    a: "Sur la liste des demandes, utilisez le filtre \"Service\" en haut. Combine avec les filtres statut et période pour cibler précisément.",
  },
  {
    id: 128,
    cat: 'rh-demandes',
    q: "Comment retrouver une demande spécifique ?",
    keywords: ['rechercher', 'trouver', 'demande spécifique'],
    a: "Barre de recherche en haut de la liste : recherche par nom d'agent, dates ou ID. Vous pouvez aussi passer par la fiche agent > onglet \"Demandes\".",
  },
  {
    id: 129,
    cat: 'rh-demandes',
    q: "Puis-je valider plusieurs demandes en une fois ?",
    keywords: ['valider plusieurs', 'masse', 'batch'],
    a: "Oui : cochez les demandes dans la liste puis cliquez sur \"Valider la sélection\". Une confirmation récapitule les agents et jours impactés avant exécution.",
  },
  {
    id: 130,
    cat: 'rh-demandes',
    q: "Que se passe-t-il si je refuse une demande ?",
    keywords: ['refuser', 'refus', 'conséquence'],
    a: "Le statut passe à \"refusée\", aucun jour n'est décompté. L'agent reçoit une notification avec votre motif et peut soumettre une nouvelle demande.",
  },

  // CET (5)
  {
    id: 131,
    cat: 'rh-cet',
    q: "Comment approuver une demande de transfert CET ?",
    keywords: ['cet', 'transfert', 'approuver', 'valider cet'],
    a: "Interface RH > \"CET\" > \"Demandes en attente\". Vérifiez l'éligibilité (1 an d'ancienneté, 20 jours pris, max 5 jours/an, plafond 60). Cliquez \"Approuver\" : les jours sont déduits du solde et ajoutés au CET.",
  },
  {
    id: 132,
    cat: 'rh-cet',
    q: "Comment refuser un transfert CET avec motif ?",
    keywords: ['cet', 'refuser', 'refus', 'transfert'],
    a: "Sur la demande CET, bouton \"Refuser\" + saisie d'un motif obligatoire (ex: ancienneté insuffisante). L'agent est notifié et la demande reste consultable dans l'historique.",
  },
  {
    id: 133,
    cat: 'rh-cet',
    q: "Comment voir le CET de chaque agent ?",
    keywords: ['cet', 'voir', 'tous', 'agents'],
    a: "Interface RH > \"CET\" > onglet \"Soldes\" : tableau de tous les agents avec leur solde CET, jours transférés cette année, et indicateur si le plafond 60 est proche.",
  },
  {
    id: 134,
    cat: 'rh-cet',
    q: "Que faire si un agent atteint le plafond de 60 jours sur son CET ?",
    keywords: ['plafond', '60', 'cet', 'maximum'],
    a: "Tout transfert au-delà est automatiquement bloqué. Proposez à l'agent une indemnisation, une consommation rapide ou une monétisation selon les règles de la collectivité.",
  },
  {
    id: 135,
    cat: 'rh-cet',
    q: "Un agent peut-il liquider son CET en argent ?",
    keywords: ['liquider', 'monétiser', 'argent', 'indemnisation'],
    a: "Selon le statut et le nombre de jours, oui. Cette opération se fait hors application (paie). Décomptez ensuite les jours liquidés depuis la fiche CET avec un motif \"liquidation\".",
  },

  // Stats & exports (5)
  {
    id: 136,
    cat: 'rh-stats',
    q: "Comment exporter les données en CSV ?",
    keywords: ['exporter', 'export', 'csv', 'excel'],
    a: "Interface RH > \"Statistiques\" > bouton \"Exporter\". Choisissez la période et le périmètre (tous services, un service, un agent). Le CSV contient demandes, soldes et historiques.",
  },
  {
    id: 137,
    cat: 'rh-stats',
    q: "Comment voir les statistiques globales de la collectivité ?",
    keywords: ['statistiques', 'global', 'tableau', 'kpi'],
    a: "Onglet \"Statistiques\" : nombre de demandes par mois, taux de validation, jours pris par service, top consommateurs. Filtres par période et type de congé.",
  },
  {
    id: 138,
    cat: 'rh-stats',
    q: "Comment générer un rapport mensuel ?",
    keywords: ['rapport', 'mensuel', 'mois', 'bilan'],
    a: "Stats > sélectionnez le mois > bouton \"Rapport mensuel\". Génère un PDF avec récapitulatif par service, anomalies (négatifs, dépassements) et top 10.",
  },
  {
    id: 139,
    cat: 'rh-stats',
    q: "Comment voir qui a pris le plus de congés cette année ?",
    keywords: ['classement', 'top', 'plus', 'consommateurs'],
    a: "Stats > onglet \"Classement\" : tri descendant par jours pris, filtrable par service. Permet de repérer les disparités et anticiper les fins d'année tendues.",
  },
  {
    id: 140,
    cat: 'rh-stats',
    q: "Puis-je extraire les données d'un seul agent ?",
    keywords: ['un agent', 'individuel', 'fiche', 'extraction'],
    a: "Oui : fiche agent > bouton \"Exporter\" > génère un PDF/CSV avec toutes les demandes, soldes et historiques de l'agent sur la période choisie. Utile pour entretiens individuels.",
  },

  // Hiérarchie (5)
  {
    id: 141,
    cat: 'rh-hierarchy',
    q: "Comment définir le responsable hiérarchique d'un agent ?",
    keywords: ['responsable', 'manager', 'hiérarchique', 'définir'],
    a: "Sur la fiche agent, champ \"Responsable hiérarchique\" : sélectionnez parmi la liste des agents ayant un niveau de validation > 0. Toutes les futures demandes remonteront à lui.",
  },
  {
    id: 142,
    cat: 'rh-hierarchy',
    q: "Comment changer le manager de plusieurs agents en une fois ?",
    keywords: ['changer manager', 'masse', 'plusieurs', 'service'],
    a: "Onglet \"Organigramme\" > sélectionnez un service > bouton \"Réaffecter\" > choisissez le nouveau manager. Toutes les demandes en cours sont reroutées automatiquement.",
  },
  {
    id: 143,
    cat: 'rh-hierarchy',
    q: "Comment configurer les niveaux de validation ?",
    keywords: ['niveaux', 'validation', 'circuit'],
    a: "Sur la fiche agent, champ \"Niveau de validation\" (0 = simple agent, 1 = responsable, 2 = chef de service, etc.). Plus le niveau est élevé, plus l'agent peut valider.",
  },
  {
    id: 144,
    cat: 'rh-hierarchy',
    q: "Que faire si un manager est en congé et qu'il y a des demandes en attente ?",
    keywords: ['absent', 'délégation', 'remplaçant'],
    a: "Vous pouvez valider à sa place en tant que RH. Pour automatiser, configurez un \"délégataire\" sur sa fiche : pendant ses congés, ses demandes en attente lui sont transférées.",
  },
  {
    id: 145,
    cat: 'rh-hierarchy',
    q: "Comment voir l'organigramme complet ?",
    keywords: ['organigramme', 'arbre', 'hiérarchie', 'voir'],
    a: "Onglet \"Organigramme\" : vue arborescente des services et de leur hiérarchie. Cliquez sur une carte pour voir l'agent, ses subordonnés et son responsable.",
  },

  // Config & système (5)
  {
    id: 146,
    cat: 'rh-config',
    q: "Comment mettre à jour la liste des jours fériés ?",
    keywords: ['jours fériés', 'férié', 'mettre à jour'],
    a: "Les jours fériés sont synchronisés automatiquement avec l'API officielle du gouvernement français (calendrier.api.gouv.fr). Aucune saisie manuelle nécessaire.",
  },
  {
    id: 147,
    cat: 'rh-config',
    q: "Comment configurer les types de congés disponibles ?",
    keywords: ['types', 'configurer', 'congés', 'paramètres'],
    a: "Onglet \"Paramètres\" > \"Types de congés\" : activez/désactivez les types (CP, RTT, Récupération, Maladie, Enfant malade, Sans solde, Exceptionnel) selon les règles de la collectivité.",
  },
  {
    id: 148,
    cat: 'rh-config',
    q: "Comment sauvegarder la base de données ?",
    keywords: ['sauvegarde', 'backup', 'base'],
    a: "Sauvegardes automatiques quotidiennes côté hébergeur Turso. Pour un export manuel : Paramètres > \"Exporter la base\" génère un dump SQL téléchargeable.",
  },
  {
    id: 149,
    cat: 'rh-config',
    q: "Comment envoyer un message à tous les agents ?",
    keywords: ['annonce', 'broadcast', 'message', 'tous'],
    a: "Onglet \"Communication\" > \"Nouvelle annonce\". Le message s'affiche en bandeau au-dessus du tableau de bord de chaque agent jusqu'à la date d'expiration choisie.",
  },
  {
    id: 150,
    cat: 'rh-config',
    q: "Comment ajuster le délai minimum de pose des congés (7 jours) ?",
    keywords: ['délai', 'minimum', '7 jours', 'modifier'],
    a: "Paramètres > \"Règles de pose\" > \"Préavis minimum\". Modifiable de 0 à 30 jours. Attention : changer cette règle n'affecte pas les demandes déjà soumises.",
  },
];
